openapi: 3.0.0
info:
  title: Simple API
  version: 1.0.0
servers:
  - url: https://fgmq22plwl.execute-api.us-east-1.amazonaws.com/dev
paths:
  /hello:
    get:
      summary: Say hello
      parameters:
        - name: name
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /users:
    post:
      summary: Create a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string