// This file is auto-generated by @hey-api/openapi-ts

export const NewReminderSchema = {
    type: 'object',
    required: ['title', 'dueDate'],
    properties: {
        title: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        dueDate: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const ReminderSchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/NewReminder'
        },
        {
            type: 'object',
            required: ['id'],
            properties: {
                id: {
                    type: 'string',
                    format: 'uuid'
                }
            }
        }
    ]
} as const;