// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetRemindersError, GetRemindersResponse, PostRemindersData, PostRemindersError, PostRemindersResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * List all reminders
 */
export const getReminders = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetRemindersResponse, GetRemindersError, ThrowOnError>({
    ...options,
    url: '/reminders'
}); };

/**
 * Create a new reminder
 */
export const postReminders = <ThrowOnError extends boolean = false>(options: Options<PostRemindersData, ThrowOnError>) => { return (options?.client ?? client).post<PostRemindersResponse, PostRemindersError, ThrowOnError>({
    ...options,
    url: '/reminders'
}); };