// This file is auto-generated by @hey-api/openapi-ts

export type NewReminder = {
    title: string;
    description?: string;
    dueDate: string;
};

export type Reminder = NewReminder & {
    id: string;
};

export type GetRemindersResponse = (Array<Reminder>);

export type GetRemindersError = unknown;

export type PostRemindersData = {
    body: NewReminder;
};

export type PostRemindersResponse = (Reminder);

export type PostRemindersError = unknown;