/* tslint:disable */
/* eslint-disable */
/**
 * Simple API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersPost201Response
 */
export interface UsersPost201Response {
    /**
     * 
     * @type {string}
     * @memberof UsersPost201Response
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPost201Response
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPost201Response
     */
    email?: string;
}

/**
 * Check if a given object implements the UsersPost201Response interface.
 */
export function instanceOfUsersPost201Response(value: object): value is UsersPost201Response {
    return true;
}

export function UsersPost201ResponseFromJSON(json: any): UsersPost201Response {
    return UsersPost201ResponseFromJSONTyped(json, false);
}

export function UsersPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

  export function UsersPost201ResponseToJSON(json: any): UsersPost201Response {
      return UsersPost201ResponseToJSONTyped(json, false);
  }

  export function UsersPost201ResponseToJSONTyped(value?: UsersPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
    };
}

