// This file is auto-generated by @hey-api/openapi-ts

export const ReminderSchema = {
    allOf: [
        {
            type: 'object',
            required: ['id'],
            properties: {
                id: {
                    type: 'string',
                    format: 'uuid',
                    example: '12e7182jajsjs-101918sjs-1901001'
                },
                description: {
                    type: 'string',
                    example: 'This is a reminder'
                },
                createdAt: {
                    type: 'string',
                    format: 'date-time',
                    example: '2021-10-10T10:10:10Z'
                }
            }
        }
    ]
} as const;