// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetRemindersData, GetRemindersError, GetRemindersResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get All reminders
 * Get all reminders Description
 */
export const getReminders = <ThrowOnError extends boolean = false>(options?: Options<GetRemindersData, ThrowOnError>) => { return (options?.client ?? client).get<GetRemindersResponse, GetRemindersError, ThrowOnError>({
    ...options,
    url: '/reminders'
}); };