// This file is auto-generated by @hey-api/openapi-ts

export type Reminder = {
  id: string;
  description?: string;
  createdAt?: string;
};

export type GetRemindersData = {
  query?: {
    /**
     * This is for the limit number
     */
    limit?: number;
    /**
     * This is for the page number
     */
    page?: number;
  };
};

export type GetRemindersResponse = {
  reminders?: Array<Reminder>;
  /**
   * Total number of reminders
   */
  total?: number;
};

export type GetRemindersError =
  | {
      message?: string;
      /**
       * Bad Request Error Code
       */
      code?: number;
    }
  | {
      message?: string;
      /**
       * Unauthorized Error Code
       */
      code?: number;
    };
